language: node_js
node_js:
  - "9"

install:
  - npm install

before_script:
  - npm install -g jsinspect

script:
  - npm run lint
  - jsinspect ./src
  - npm run build

branches:
  only:
  - master
