export default [{
  name: 'country',
  title: 'Google trends country',
  type: 'select',
  value: 'france',
  items: [
    'romania',
    'finland',
    'portugal',
    'mexico',
    'egypt',
    'brazil',
    'united_states',
    'india',
    'malaysia',
    'austria',
    'colombia',
    'japan',
    'hungary',
    'new zealand',
    'greece',
    'taiwan',
    'canada',
    'italy',
    'france',
    'kenya',
    'ireland',
    'nigeria',
    'norway',
    'turkey',
    'israel',
    'australia',
    'singapore',
    'netherlands',
    'germany',
    'chile',
    'belgium',
    'thailand',
    'argentina',
    'spain',
    'south_korea',
    'ukraine',
    'hong_kong',
    'south_africa',
    'denmark',
    'poland',
    'indonesia',
    'czech_republic',
    'russia',
    'sweden',
    'vietnam',
    'saudi_arabia',
    'switzerland',
    'philippines',
    'united_kingdom',
  ],
}];
