export default [
  { text: 'settings.artworks.random', value: 'random' },
  { text: 'settings.artworks.unsplash', value: 'unsplash' },
  { text: 'settings.artworks.url', value: 'url' },
  { text: 'settings.artworks.local', value: 'local' },
  { text: 'settings.artworks.mountains', value: 'mountains' },
  { text: 'Austin', value: 'austin' },
  { text: 'Beach', value: 'beach' },
  { text: 'Berlin', value: 'berlin' },
  { text: 'Chicago', value: 'chicago' },
  { text: 'Great Plains', value: 'greatPlains' },
  { text: 'London', value: 'london' },
  { text: 'New York', value: 'newYork' },
  { text: 'Paris', value: 'paris' },
  { text: 'San Francisco', value: 'sanFrancisco' },
  { text: 'Seattle', value: 'seattle' },
  { text: 'Tahoe', value: 'tahoe' },
];
